export const CURRENT_TERMS_VERSION = "2026-06-09";
export const RAPIV_BUSINESS_COMMISSION_PERCENT = 7;
export const RAPIV_DELIVERY_OPERATION_FEE_MXN = 5;
export const RAPIV_COURIER_PAYOUT_MXN = 25;
export const RAPIV_CUSTOMER_DELIVERY_FEE_MXN = 30;
