export const colors = {
  background: "#F8FAFC",
  surface: "#FFFFFF",
  text: "#0F172A",
  muted: "#64748B",
  border: "#E2E8F0",
  primary: "#2563EB",
  primaryLight: "#EFF6FF",
  primaryBand: "#DBEAFE",
  primaryBorder: "#BFDBFE",
  secondary: "#22C55E",
  secondaryLight: "#F0FDF4",
  secondaryBorder: "#BBF7D0",
  disabled: "#CBD5E1",
  warning: "#FEF3C7",
  success: "#DCFCE7",
  danger: "#FEE2E2",
  dangerText: "#DC2626",
  info: "#DBEAFE",
  textSecondary: "#475569",
} as const;
