export const colors = {
  primary: '#EA580C',
  primaryLight: '#FFF7ED',
  primaryBand: '#FED7AA',
  primaryBorder: '#FDBA74',
  secondary: '#2563EB',
  secondaryLight: '#EFF6FF',
  secondaryBorder: '#BFDBFE',
  success: '#22C55E',
  danger: '#DC2626',
  warning: '#F59E0B',
  info: '#DBEAFE',
  light: '#F8FAFC',
  dark: '#0F172A',
  background: "#F8FAFC",
  text: "#0F172A",
  border: "#E2E8F0",
  muted: "#64748B",
  surface: "#FFFFFF",
  textSecondary: "#475569",
};
