import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingBottom: 14,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.text,
  },
  refreshButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  list: {
    paddingHorizontal: 16,
    paddingBottom: 92,
  },
  stripeWorkNotice: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFBEB',
    borderColor: '#FCD34D',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
    padding: 12,
  },
  stripeWorkNoticeText: {
    color: '#92400E',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 14,
  },
  cardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  orderId: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
    color: colors.text,
  },
  orderStatus: {
    color: colors.primary,
    fontWeight: '700',
    marginBottom: 8,
  },
  statusBadge: {
    backgroundColor: '#EFF6FF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgeText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  offerBadge: {
    backgroundColor: '#ECFDF5',
  },
  offerBadgeText: {
    color: colors.success,
  },
  deliveredBadge: {
    backgroundColor: '#F1F5F9',
  },
  deliveredBadgeText: {
    color: colors.muted,
  },
  orderMeta: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 4,
  },
  payoutPanel: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
    marginTop: 10,
    padding: 12,
  },
  payoutLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  payoutAmount: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 2,
  },
  payoutBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  payoutBadgePending: {
    backgroundColor: '#FFFBEB',
  },
  payoutBadgePaid: {
    backgroundColor: '#ECFDF5',
  },
  payoutBadgeFailed: {
    backgroundColor: '#FEF2F2',
  },
  payoutBadgeText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  payoutBadgeTextPending: {
    color: '#92400E',
  },
  payoutBadgeTextPaid: {
    color: colors.success,
  },
  payoutBadgeTextFailed: {
    color: '#B91C1C',
  },
  payoutDetail: {
    color: colors.textSecondary,
    flexBasis: '100%',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  flowNotice: {
    backgroundColor: '#F8FAFC',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 10,
    marginTop: 8,
    padding: 10,
  },
  multiFlowNotice: {
    backgroundColor: '#ECFEFF',
    borderColor: '#67E8F9',
  },
  flowTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '900',
  },
  flowBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  phoneButton: {
    alignSelf: 'flex-start',
    marginBottom: 4,
    paddingVertical: 4,
  },
  phoneText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  sectionTitle: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  orderItem: {
    color: colors.text,
    fontSize: 14,
    marginTop: 2,
  },
  pickupRow: {
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 8,
    padding: 10,
  },
  readyPickupRow: {
    backgroundColor: '#F0FDF4',
    borderColor: '#86EFAC',
  },
  pickedUpRow: {
    backgroundColor: '#F8FAFC',
  },
  pickupHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  pickupTextGroup: {
    flex: 1,
  },
  pickupTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  pickupAddress: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },
  pickupActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  pickupRouteButton: {
    alignItems: 'center',
    borderColor: colors.primary,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 10,
  },
  pickupRouteText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  pickupButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
  },
  pickupButtonText: {
    color: colors.surface,
    fontSize: 12,
    fontWeight: '800',
  },
  pickupItem: {
    color: colors.text,
    fontSize: 12,
    marginTop: 6,
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    marginTop: 14,
    paddingVertical: 12,
  },
  routeButton: {
    alignItems: 'center',
    borderColor: colors.primary,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
    paddingVertical: 11,
  },
  routeText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  arrivalButton: {
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderColor: '#86EFAC',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
    paddingVertical: 11,
  },
  arrivalText: {
    color: colors.success,
    fontSize: 14,
    fontWeight: '900',
  },
  map: {
    borderRadius: 8,
    height: 220,
    marginTop: 12,
    overflow: 'hidden',
  },
  actionText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '800',
  },
  disabledButton: {
    opacity: 0.6,
  },
  tabBar: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    left: 0,
    paddingHorizontal: 10,
    paddingTop: 8,
    position: 'absolute',
    right: 0,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    gap: 3,
    paddingVertical: 8,
  },
  activeTabButton: {
    backgroundColor: '#EFF6FF',
  },
  tabLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  activeTabLabel: {
    color: colors.primary,
  },
  profileContent: {
    paddingHorizontal: 16,
    paddingBottom: 108,
  },
  profileCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    padding: 20,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderRadius: 999,
    height: 70,
    justifyContent: 'center',
    width: 70,
  },
  avatarText: {
    color: colors.primary,
    fontSize: 30,
    fontWeight: '900',
  },
  profileName: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 12,
    textAlign: 'center',
  },
  profileEmail: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: 4,
    textAlign: 'center',
  },
  availabilityPill: {
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    marginTop: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  busyPill: {
    backgroundColor: '#FFFBEB',
  },
  availabilityText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  metricsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  metricCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    padding: 12,
  },
  metricValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  infoCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 14,
    padding: 16,
  },
  infoRow: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 10,
  },
  infoTextBlock: {
    flex: 1,
  },
  infoTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  infoText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  profileEditHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  editProfileText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
  },
  profileForm: {
    gap: 10,
  },
  profileInput: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.text,
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  profileError: {
    color: '#B91C1C',
    fontSize: 13,
    fontWeight: '700',
  },
  saveProfileButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 12,
  },
  saveProfileText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '900',
  },
  stripeActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  stripeButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 10,
  },
  stripeButtonText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  stripeButtonSecondary: {
    alignItems: 'center',
    borderColor: colors.primary,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 10,
  },
  stripeButtonSecondaryText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  stripeError: {
    color: '#B91C1C',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 10,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 14,
    paddingVertical: 13,
  },
  logoutText: {
    color: '#B91C1C',
    fontSize: 14,
    fontWeight: '900',
  },
  cashPanel: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FCD34D',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    marginTop: 10,
    padding: 12,
  },
  cashTitle: {
    color: '#92400E',
    fontSize: 14,
    fontWeight: '900',
  },
  cashText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  cashInput: {
    backgroundColor: colors.surface,
    borderColor: '#F59E0B',
    borderRadius: 8,
    borderWidth: 1,
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  cashChange: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
  },
});
